#Config database example
#Change this to your MySQL URL
db.url=jdbc:mysql://localhost:3307/vetcare-management 
#Change this to your MySQL username
db.username=root
#Change this to your MySQL password
db.password=root